#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi





# My customisation

alias editzsh='emacs ~/.zprezto/brad.custom.zsh'

alias ls='ls -al --color'
alias sc='screen -dR'

alias m='python manage.py'
alias delpyc='find -name "*.pyc" -delete'
alias optimise_jpgs='mkdir optimised; for i in *.JPG; do jpegoptim "$i" --max=80 --dest="optimised"; done'

# grep global aliases
alias -g '[py]'='--include="*.py"'
alias -g '[js]'='--include="*.js"'
alias -g '[less]'='--include="*.less"'
alias -g '[css]'='--include="*.css"'
alias -g '[html]'='--include="*.html"'

function fname() { find . -iname "*$@*"; }

# Temporary hack! This (potentially) fixes slow wifi when on battery power by
# turning off power-saving features.
# http://ubuntuforums.org/showthread.php?t=1678098
alias fix_slow_wifi='sudo iwconfig wlan0 power off'

# GPG
alias gpg-import='gpg --import ~/Downloads/address.txt'
function gpg-encrypt {
    gpg --recipient $1 --output ~/Downloads/message.gpg --armor --encrypt ~/Downloads/message.txt
}

# upload a file for temporary (2 week) sharing via http://transfer.sh/
function transfer() { curl --upload-file ./$1 https://transfer.sh/$1; }
alias transfer=transfer

# interactive move
# very useful; even creates the directory if it doesn't exist
imv() {
  local src dst
  for src; do
    [[ -e $src ]] || { print -u2 "$src does not exist"; continue }
    dst=$src
    vared dst
    [[ $src != $dst ]] && mkdir -p $dst:h && mv -n $src $dst
  done
}

# Make git branch autocompletion not painfully slow
# http://superuser.com/questions/458906/zsh-tab-completion-of-git-commands-is-very-slow-how-can-i-turn-it-off
__git_files () {
    _wanted files expl 'local files' _files
}

# run custom zsh file if exists
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/brad.custom.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/brad.custom.zsh"
fi
